services:
  # PHẦN LƯU TRỮ VÀ REDIS
  postgres_db:
    image: postgres:15-alpine 
    container_name: uet_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: uet_rag_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - rag_network
  

  qdrant_db:
    image: qdrant/qdrant:latest
    container_name: uet_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    networks:
      - rag_network

  
  minio_storage:
    image: minio/minio:latest
    container_name: uet_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped
    networks:
      - rag_network

  redis_broker:
    image: redis:7-alpine
    container_name: uet_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - rag_network


# PHẦN XỬ LÝ LOGIC NGHIỆP VỤ

  worker:
    build:
      context: ./worker
    container_name: uet_worker
    #HOC THAT KY
    environment:
      - QDRANT_URL=http://qdrant_db:6333
      - REDIS_URL=redis://redis_broker:6379/0
      - MINIO_URL=http://minio_storage:9000
    volumes:
      - ./worker:/app
    depends_on:
      - postgres_db
      - qdrant_db
      - redis_broker
    networks:
      - rag_network

# PHẦN XỬ LÝ GIAO DIỆN VÀ NGINX

  frontend_login:
    build:
      context: ./frontend-login
    container_name: uet_frontend_login
    restart: unless-stopped
    ports:
      - "5000:80"
    depends_on:
      - backend-api
    networks:
      - rag_network

  frontend_user:
    build:
      context: ./frontend-user
    container_name: uet_frontend_user
    restart: unless-stopped
    ports:
      - "4000:80"
    depends_on:
      - backend-api
    networks:
      - rag_network

  frontend_admin:
    build:
      context: ./frontend-admin
    container_name: uet_frontend_admin
    restart: unless-stopped
    ports:
      - "4001:80"
    depends_on:
      - backend-api
    networks:
      - rag_network
  
  nginx_gateway:
    image: nginx:alpine
    container_name: uet_nginx
    ports: 
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-api
      - frontend_user
      - frontend_admin
    networks:
      - rag_network
  #OLLAMA
  ollama:
    image: ollama/ollama:latest
    container_name: uet_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - rag_network

  backend-api:
    build:
      context: ./backend-api
    container_name: uet_backend_api
    #hoc ky phan nay
    environment:
      - DATABASE_URL=postgresql://user:password@postgres_db:5432/uet_rag_db
      - QDRANT_URL=http://qdrant_db:6333
      - REDIS_URL=redis://redis_broker:6379/0
      - LLM_API_BASE=http://ollama:11434/v1
      - SECRET_KEY=UET_RAG_SUPER_SECRET_KEY_2026
    ports:
      - "8000:8000"
    volumes:
      - ./backend-api:/app
    depends_on:
      - ollama
      - postgres_db
      - qdrant_db
      - redis_broker
    networks:
      - rag_network

# KHAI BÁO CÁC NETWORK VÀ VOLUMES
networks:
  rag_network:
    driver: bridge
  
volumes:
  postgres_data:
  qdrant_data:
  minio_data:
  redis_data:
  ollama_data: