# Sử dụng Node.js bản ổn định Long Term Support
FROM node:20-alpine

WORKDIR /app

# Lệnh tạm thời giữ container Frontend luôn sống
CMD ["sh", "-c", "echo 'Frontend dang san sang...'; while true; do sleep 3600; done"]