events { worker_connections 1024; }

http {
    server {
        listen 80;

        location / {
            return 200 'UET RAG System - He thong dang khoi tao thanh cong!';
            add_header Content-Type text/plain;
        }
    }
}